### ISSUE TITLE
Crashes while trying to add a new service to an existing environment

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/kam#102]
**Describe the bug**
`kam` crashes while trying to add a new service to an existing environment

**To Reproduce**
1.  Bootstrapped https://github.com/sbose78/graphtuitous using interactive mode

2. Tried adding a service to an existing env.

```
kam service add --env-name stage --app-name app-graphtuitous --service-name graphtuitous --sealed-secrets-ns sealed-secrets --sealed-secrets-svc sealed-secrets-controller --image-repo=quay.io/shbose/graphtuitous
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x220ad2a]

goroutine 1 [running]:
github.com/redhat-developer/kam/pkg/pipelines.serviceResources(0xc0008f0780, 0x28ac100, 0xc0008fd110, 0xc00089bc20, 0xc0008f0780, 0x0, 0x0)
	/Users/sbose/kam/pkg/pipelines/service.go:112 +0x91a
github.com/redhat-developer/kam/pkg/pipelines.AddService(0xc00089bc20, 0x28ac100, 0xc0008fd110, 0xc0008fd110, 0xc000571ce0)
	/Users/sbose/kam/pkg/pipelines/service.go:42 +0xb4
github.com/redhat-developer/kam/pkg/cmd/service.(*AddServiceOptions).Run(0xc0000cb578, 0x0, 0x0)
	/Users/sbose/kam/pkg/cmd/service/add.go:49 +0x83
github.com/redhat-developer/kam/pkg/cmd/genericclioptions.GenericRun(0x2879d00, 0xc0000cb578, 0xc0009182c0, 0xc0008d24d0, 0x0, 0xb)
	/Users/sbose/kam/pkg/cmd/genericclioptions/runnable.go:25 +0xf2
github.com/redhat-developer/kam/pkg/cmd/service.newCmdAdd.func1(0xc0009182c0, 0xc0008d24d0, 0x0, 0xb)
	/Users/sbose/kam/pkg/cmd/service/add.go:67 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0009182c0, 0xc0008d2420, 0xb, 0xb, 0xc0009182c0, 0xc0008d2420)
	/Users/sbose/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008b5600, 0x1007abf, 0xc0000a8058, 0x0)
	/Users/sbose/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sbose/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/redhat-developer/kam/pkg/cmd.Execute()
	/Users/sbose/kam/pkg/cmd/kam.go:42 +0x27
main.main()
	/Users/sbose/kam/cmd/kam/kam.go:8 +0x20
```

**Expected behavior**
```
 ✓  Created Service graphtuitous successfully at environment stage.
```

**Screenshots**

**Additional context**

**Comment by bigkevmcd** [comment]
This is because you're adding it to an environment with no defined pipelines, but with an image.

What should it do? Our current default pipelines are for building the image.

Should we assume that you want the same pipeline across all environments?

It's definitely possible that you might want to execute a pipeline for a repo on push.

**Comment by sbose78** [comment]
Here's how I am thinking, if I'm adding a new service to an env, I would either
* Add a service with no code repo to build ( no "image build" pipelines needed ) 
* Add a service a code repo ( "image Build" pipelines would be needed )

**Comment by bigkevmcd** [comment]
Just to be clear, you added it to the "stage" environment, you expected to rebuild the image in stage before going to the next stage?

**Comment by sbose78** [comment]
Correct

**Comment by bigkevmcd** [comment]
What's going to trigger the pipeline?

Is this for manual processes?

Do we just duplicate the "previous" stage's pipelines if there aren't any?

**Comment by sbose78** [comment]
> What's going to trigger the pipeline?

* If the service includes a new application source code repo, PRs to the application source code repo should trigger the pipeline. 
* If the service doesn't include any new application source code repo, then we don't need any new pipelines ( other than dry run pipelines for gitops repo which already exists ).


What do you think? 🤔

**Comment by bigkevmcd** [comment]
It doesn't cover the rebuild the image part?

**Comment by bigkevmcd** [comment]
The problem I can see, is that we'll receive a push notification, we can trigger in multiple pipelines, which will trigger images being built in each stage, while this will sort of rebuild, it's not clear the benefit of the rebuild at this point, because it would trigger the build on the trunk branch too?

**Comment by sbose78** [comment]
yeah image from the application source code repo needs to be built 'once'.

**Comment by sbose78** [comment]
but then, we are effectively starting to talk like `applications/services` as a top-level constructs instead of environments being the top-level construct :)

**Comment by bigkevmcd** [comment]
> Just to be clear, you added it to the "stage" environment, you expected to rebuild the image in stage before going to the next stage?

So, we rebuild it, but only once? Are we basing that on a specific branch?

i.e. in your application code, are we talking about building the "production" branch into production?
