### ISSUE TITLE
kam should trim leading and trailing spaces from input

### ISSUE THREAD

**Issue by keithchong** [redhat-developer/kam#142]
**Describe the bug**
kam exits with error if the user provides answers with leading spaces in their response.  Trailing spaces can pose problems as well.

**To Reproduce**
1. Run kam bootstrap
2. When prompted to enter the URL for your GitOps repository, purposely add a space before your gitops URL
3. Hit enter

kam exits with an error

See output below:

```
kam bootstrap
  
Checking dependencies

 ✓  Checking if Sealed Secrets is installed with the default configuration [325ms]
 ✓  Checking if ArgoCD Operator is installed with the default configuration [721ms]
 ✓  Checking if OpenShift Pipelines Operator is installed with the default configuration [846ms]
  
Starting interactive prompt

? Provide the URL for your GitOps repository  https://github.com/keithchong/gitops9.git
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1fadcb7]

goroutine 1 [running]:
github.com/redhat-developer/kam/pkg/cmd/ui.EnterGitRepo(0xc0002ed820, 0x2659cf6)
	/Users/kchong/wrh/git/kam/pkg/cmd/ui/ui.go:26 +0x117
github.com/redhat-developer/kam/pkg/cmd.initiateInteractiveMode(0xc00007fd50, 0xc0002ed820, 0x2874620, 0xc000495500)
	/Users/kchong/wrh/git/kam/pkg/cmd/bootstrap.go:161 +0x9d
github.com/redhat-developer/kam/pkg/cmd.(*BootstrapParameters).Complete(0xc00007fd50, 0x265fca6, 0x9, 0xc0004fe2c0, 0x34268e8, 0x0, 0x0, 0xc00018fc00, 0x2659e0a)
	/Users/kchong/wrh/git/kam/pkg/cmd/bootstrap.go:112 +0x14c
github.com/redhat-developer/kam/pkg/cmd/genericclioptions.GenericRun(0x2874660, 0xc00007fd50, 0xc0004fe2c0, 0x34268e8, 0x0, 0x0)
	/Users/kchong/wrh/git/kam/pkg/cmd/genericclioptions/runnable.go:23 +0x6e
github.com/redhat-developer/kam/pkg/cmd.NewCmdBootstrap.func1(0xc0004fe2c0, 0x34268e8, 0x0, 0x0)
	/Users/kchong/wrh/git/kam/pkg/cmd/bootstrap.go:324 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0004fe2c0, 0x34268e8, 0x0, 0x0, 0xc0004fe2c0, 0x34268e8)
	/Users/kchong/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004fe000, 0x1008285, 0xc0000ae058, 0x0)
	/Users/kchong/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/kchong/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/redhat-developer/kam/pkg/cmd.Execute()
	/Users/kchong/wrh/git/kam/pkg/cmd/kam.go:42 +0x2a
main.main()
	/Users/kchong/wrh/git/kam/cmd/kam/kam.go:8 +0x25

```

**Expected behavior**
kam should trim spaces. I discovered this problem when I copied and pasted the repo, and I inadvertantly copied a leading space.

**Comment by keithchong** [comment]
My changes for this fix conflict with the changes for the smart defaults changes in https://github.com/redhat-developer/kam/pull/148

This fix should be in a separate PR because it's a different problem. 

So either I create a separate PR based off master which will probably result in 148 having conflicts, or create the PR after 148 has been merged. Because this one is a smaller, less complicated fix, I think the latter is preferable.
